apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: pooja-platform
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8087"
    spec:
      containers:
        - name: notification-service
          image: pooja-platform/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: pooja-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pooja-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pooja-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: pooja-platform
spec:
  selector:
    app: notification-service
  ports:
    - port: 8087
      targetPort: 8087

