import { Product, Pandit } from './types';

export const CATEGORIES = [
  { id: 'puja-kits', name: 'Puja Kits', nameHi: 'पूजा किट', icon: '🪔' },
  { id: 'idols-murtis', name: 'Idols & Murtis', nameHi: 'मूर्तियां', icon: '🙏' },
  { id: 'incense-dhoop', name: 'Incense & Dhoop', nameHi: 'अगरबत्ती', icon: '🌿' },
  { id: 'diyas-lamps', name: 'Diyas & Lamps', nameHi: 'दीये', icon: '🕯️' },
  { id: 'spiritual-books', name: 'Spiritual Books', nameHi: 'आध्यात्मिक पुस्तकें', icon: '📖' },
  { id: 'rudraksha', name: 'Rudraksha & Malas', nameHi: 'रुद्राक्ष', icon: '📿' },
  { id: 'havan-samagri', name: 'Havan Samagri', nameHi: 'हवन सामग्री', icon: '🔥' },
  { id: 'flowers-garlands', name: 'Flowers & Garlands', nameHi: 'फूल-माला', icon: '💐' },
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Complete Ganesh Chaturthi Puja Kit',
    description: 'Everything you need for Ganesh Chaturthi celebrations. Includes eco-friendly Ganesh idol, modak mould, durva grass, red flowers, coconut, and all essential puja items with detailed instruction booklet.',
    category: 'puja-kits',
    price: 1499,
    originalPrice: 1999,
    currency: 'INR',
    imageUrl: 'https://images.unsplash.com/photo-1567591370504-80d5e4dd3925?w=600',
    tags: ['ganesh', 'chaturthi', 'festival', 'eco-friendly'],
    sellerId: 's1',
    sellerName: 'Divine Essentials',
    stock: 150,
    rating: 4.8,
    reviewCount: 234,
    featured: true,
    approved: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Handcrafted Brass Diya Set (5 pcs)',
    description: 'Beautiful handcrafted brass diyas with intricate traditional designs. Perfect for daily puja, Diwali, and festive decorations. Comes with cotton wicks.',
    category: 'diyas-lamps',
    price: 899,
    originalPrice: 1299,
    currency: 'INR',
    imageUrl: 'https://images.unsplash.com/photo-1605649461121-64126a96b9a4?w=600',
    tags: ['brass', 'diya', 'diwali', 'handcrafted'],
    sellerId: 's2',
    sellerName: 'Artisan Crafts',
    stock: 300,
    rating: 4.6,
    reviewCount: 189,
    featured: true,
    approved: true,
    createdAt: '2024-02-10',
  },
  {
    id: '3',
    name: 'Premium Nag Champa Agarbatti (12 boxes)',
    description: 'Hand-rolled premium quality Nag Champa incense sticks. Made with natural ingredients and traditional methods. Each box contains 20 sticks with a burn time of 45 minutes.',
    category: 'incense-dhoop',
    price: 449,
    currency: 'INR',
    imageUrl: 'https://images.unsplash.com/photo-1602519037249-a2a1c268940e?w=600',
    tags: ['agarbatti', 'nag-champa', 'incense', 'natural'],
    sellerId: 's1',
    sellerName: 'Divine Essentials',
    stock: 500,
    rating: 4.9,
    reviewCount: 567,
    featured: true,
    approved: true,
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Navratri Special Pooja Thali Set',
    description: 'Complete decorated pooja thali with kalash, coconut holder, roli-chawal, bell, and aarti lamp. Gold-finished stainless steel with meenakari work.',
    category: 'puja-kits',
    price: 2499,
    originalPrice: 3299,
    currency: 'INR',
    imageUrl: 'https://images.unsplash.com/photo-1621450605965-bd0c3bb07c7f?w=600',
    tags: ['navratri', 'thali', 'pooja', 'festival'],
    sellerId: 's3',
    sellerName: 'Festival Store',
    stock: 75,
    rating: 4.7,
    reviewCount: 122,
    featured: true,
    approved: true,
    createdAt: '2024-03-01',
  },
  {
    id: '5',
    name: '5 Mukhi Rudraksha Mala (108 beads)',
    description: 'Certified genuine 5 Mukhi Rudraksha mala with 108 beads from Nepal. Knotted with silk thread and silver capping. Comes with authenticity certificate.',
    category: 'rudraksha',
    price: 3999,
    originalPrice: 5499,
    currency: 'INR',
    imageUrl: 'https://images.unsplash.com/photo-1611516491426-03025e6043c8?w=600',
    tags: ['rudraksha', 'mala', 'nepal', 'certified'],
    sellerId: 's4',
    sellerName: 'Sacred Beads',
    stock: 50,
    rating: 4.9,
    reviewCount: 89,
    featured: true,
    approved: true,
    createdAt: '2024-02-15',
  },
  {
    id: '6',
    name: 'Havan Samagri Premium Mix (1kg)',
    description: 'Premium quality havan samagri with 51 sacred herbs and ingredients. Includes guggul, camphor, sandalwood chips, dried rose petals, and more. Vacuum sealed for freshness.',
    category: 'havan-samagri',
    price: 599,
    currency: 'INR',
    imageUrl: 'https://images.unsplash.com/photo-1609766418204-94aae0161668?w=600',
    tags: ['havan', 'samagri', 'herbs', 'fire-ceremony'],
    sellerId: 's1',
    sellerName: 'Divine Essentials',
    stock: 200,
    rating: 4.5,
    reviewCount: 334,
    featured: false,
    approved: true,
    createdAt: '2024-03-10',
  },
];

export const SAMPLE_PANDITS: Pandit[] = [
  {
    id: 'p1',
    userId: 'u1',
    name: 'Pandit Ramesh Sharma',
    title: 'Vedic Scholar & Ritualist',
    bio: 'With over 25 years of experience in Vedic rituals and ceremonies, Pandit Ramesh Sharma is renowned for his deep knowledge of Sanskrit scriptures and traditional pooja practices. Specializing in Griha Pravesh, Satyanarayan Katha, and wedding ceremonies.',
    profileImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    specializations: ['Griha Pravesh', 'Satyanarayan Katha', 'Wedding Ceremonies', 'Navgraha Shanti'],
    languages: ['Hindi', 'Sanskrit', 'English'],
    experience: 25,
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    rating: 4.9,
    reviewCount: 312,
    pricePerHour: 2100,
    pricePerCeremony: 5100,
    virtualAvailable: true,
    verified: true,
    createdAt: '2023-06-15',
  },
  {
    id: 'p2',
    userId: 'u2',
    name: 'Acharya Priya Devi',
    title: 'Astrologer & Puja Specialist',
    bio: 'Acharya Priya Devi combines traditional Vedic astrology with ritual practices. She is one of the few women pandits offering complete ceremony services including Ganesh Puja, Lakshmi Puja, and Sundarkand path. Known for her soulful chanting.',
    profileImageUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400',
    specializations: ['Ganesh Puja', 'Lakshmi Puja', 'Sundarkand', 'Astrology Consultation'],
    languages: ['Hindi', 'Marathi', 'English'],
    experience: 15,
    city: 'Pune',
    state: 'Maharashtra',
    rating: 4.8,
    reviewCount: 198,
    pricePerHour: 1800,
    pricePerCeremony: 4500,
    virtualAvailable: true,
    verified: true,
    createdAt: '2023-08-20',
  },
  {
    id: 'p3',
    userId: 'u3',
    name: 'Pandit Suresh Iyer',
    title: 'South Indian Rituals Expert',
    bio: 'Specializing in South Indian temple-style pujas and homams. Pandit Suresh Iyer conducts elaborate fire ceremonies, Ayush Homam, Ganapathy Homam, and all Tamil Nadu traditional ceremonies with authentic mantras.',
    profileImageUrl: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?w=400',
    specializations: ['Homam', 'Ayush Homam', 'Ganapathy Homam', 'Tamil Ceremonies'],
    languages: ['Tamil', 'Sanskrit', 'English', 'Telugu'],
    experience: 20,
    city: 'Chennai',
    state: 'Tamil Nadu',
    rating: 4.7,
    reviewCount: 156,
    pricePerHour: 1500,
    pricePerCeremony: 3500,
    virtualAvailable: true,
    verified: true,
    createdAt: '2023-07-10',
  },
  {
    id: 'p4',
    userId: 'u4',
    name: 'Pandit Devendra Joshi',
    title: 'Muhurat & Vastu Specialist',
    bio: 'Expert in Muhurat calculations and Vastu Shastra consultations. Pandit Devendra Joshi helps families find auspicious timings for weddings, business openings, and property purchases. Also conducts all major Hindu ceremonies.',
    profileImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
    specializations: ['Muhurat Consultation', 'Vastu Shastra', 'Wedding Planning', 'Business Puja'],
    languages: ['Hindi', 'Gujarati', 'English'],
    experience: 18,
    city: 'Ahmedabad',
    state: 'Gujarat',
    rating: 4.6,
    reviewCount: 143,
    pricePerHour: 2500,
    pricePerCeremony: 7000,
    virtualAvailable: false,
    verified: true,
    createdAt: '2023-09-01',
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Ananya Desai',
    location: 'Mumbai',
    text: 'The Ganesh Chaturthi kit was perfect! Everything was so well organized and the quality of items exceeded my expectations. Panditji guided us through the entire puja virtually.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Rajesh Kumar',
    location: 'Delhi',
    text: 'Booked Pandit Ramesh for our Griha Pravesh ceremony. His knowledge and dedication made the whole experience truly divine. Highly recommended!',
    rating: 5,
  },
  {
    id: 3,
    name: 'Meera Nair',
    location: 'Bangalore',
    text: 'The AI assistant helped me understand the significance of each step in our Navratri puja. The platform is a blessing for families living away from home.',
    rating: 5,
  },
];

export const RITUAL_GUIDES = [
  {
    id: 1,
    title: 'Ganesh Chaturthi',
    description: 'Complete guide to Ganesh Chaturthi celebrations including Pranapratishtha, offerings, and Visarjan rituals.',
    icon: '🙏',
  },
  {
    id: 2,
    title: 'Navratri & Durga Puja',
    description: 'Nine nights of devotion — learn about garba, aarti, and daily color significance.',
    icon: '🪷',
  },
  {
    id: 3,
    title: 'Diwali Lakshmi Puja',
    description: 'Step-by-step Lakshmi puja vidhi for prosperity and auspiciousness.',
    icon: '🪔',
  },
  {
    id: 4,
    title: 'Satyanarayan Katha',
    description: 'Understanding the five chapters of Satyanarayan Vrat Katha and its significance.',
    icon: '📖',
  },
];
